sonar.projectKey=kata-evaluacion-tecnica
sonar.projectName=Plataforma de Evaluacion Tecnica
sonar.sourceEncoding=UTF-8

sonar.sources=backend/src/main/java,frontend/src
sonar.tests=backend/src/test/java,frontend/src
sonar.test.inclusions=**/*Test.java,**/*.spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/.angular/**,frontend/public/**
sonar.coverage.exclusions=frontend/**,**/AplicacionKata.java

sonar.java.binaries=backend/target/classes
sonar.java.source=21
sonar.coverage.jacoco.xmlReportPaths=backend/target/site/jacoco/jacoco.xml
